# Generated by Django 5.1 on 2024-08-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_publisher_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
